name: Upload coverage reports to Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Julia 1.9.0
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.9.0"
      
      - name: Build package
        uses: julia-actions/julia-buildpkg@v1
      
      - name: Build test dependencies
        run: |
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
        shell: julia --project=test {0}
      
      - name: Run tests
        uses: julia-actions/julia-runtest@v1
      
      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1
      
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: aclai-lab/SoleModels.jl